name: architecture_template
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.8

  #Core
  equatable: ^2.0.5

  #Network
  vexana: ^5.0.1

  #State
  flutter_riverpod: ^2.5.1
  
  #Config
  json_annotation: ^4.9.0
  envied: ^0.5.4+1
  easy_localization: ^3.0.7

  #Utility
  easy_logger: ^0.0.2
  logger: ^2.4.0
  kartal: ^4.1.0

  widgets:
    path: module/widgets
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^6.0.0
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  flutter_launcher_icons: "^0.14.1"
  envied_generator: ^0.5.4+1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/app_icon.png"
  min_sdk_android: 21 
  remove_alpha_ios: true

flutter_gen:
  output: lib/product/generated
  integrations:
    lottie: true


flutter:

  
  uses-material-design: true

  assets:
    - asset/translations/

  