name: architecture_template
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.8

  #Core
  equatable: ^2.0.5
  get_it: ^8.0.0

  #Network
  vexana: ^5.0.1

  #State
  flutter_bloc: ^8.1.6

  #Config
  easy_localization: ^3.0.7

  #Utility
  easy_logger: ^0.0.2
  logger: ^2.4.0
  kartal: ^4.1.0
  google_fonts: ^6.2.1

  #Nav
  auto_route: ^9.2.2

  widgets:
    path: module/widgets

  gen:
    path: module/gen

  common:
    path: module/common
    

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^6.0.0
  flutter_launcher_icons: "^0.14.1"
  build_runner: ^2.4.13
  auto_route_generator: ^9.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/app_icon.png"
  min_sdk_android: 21 
  remove_alpha_ios: true




flutter:

  
  uses-material-design: true

  assets:
    - asset/translations/

  